version: "3"

networks:
  imagineapi_imagineapi_net:
    external: true

services:
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      - imagineapi_imagineapi_net
